# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: 'pip'
    directory: '/'
    # Check the pip registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
    versioning-strategy: 'increase'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    # Check the github-actions registry for updates every week (Monday)
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
    versioning-strategy: 'increase'

  # Enable version updates for uv
  - package-ecosystem: 'uv'
    directory: '/'
    # Check the uv registry for updates every week (Monday)
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
    versioning-strategy: 'increase'

  # Enable version updates for git submodules
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    # Check the git submodules for updates every week (Monday)
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
    versioning-strategy: 'increase'
