[tool.poetry]
name = "ttml-validator"
version = "0.1.0"
description = "Utility for validating TTML-like files against the BBC Subtitle Guidelines EBU-TT-D requirements."
authors = ["Nigel Megitt <nigel.megitt@bbc.co.uk>"]
readme = "README.md"
packages = [
    { include = "src" },
    { include = "test" }
]

[tool.poetry.dependencies]
python = "^3.11.7"
xmlschema = "^4.0.1"

[tool.poetry.group.dev.dependencies]
pydocstyle = "^6.3.0"
flake8 = "^7.2.0"
coverage = "^7.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
validate-ttml = "src.ttmlValidator:main"
collate-validation-results = "src.validationCollater:main"
