[project]
name = "ttml-validator"
version = "0.1.0"
description = "Utility for validating TTML-like files against the BBC Subtitle Guidelines EBU-TT-D requirements."
authors = [ {name = "Nigel Megitt <nigel.megitt@bbc.co.uk>"} ]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "xmlschema == 4.2.0",
    "charset-normalizer == 3.4.4"
]

[project.scripts]
validate-ttml = "src.ttmlValidator:main"
collate-validation-results = "src.validationCollater:main"

[tool.poetry]
packages = [
    { include = "src" },
    { include = "test" }
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "coverage==7.13.0",
    "debugpy==1.8.19",
    "sphinx==9.0.4",
    "flake8==7.3.0",
    "pydocstyle==6.3.0",
]
