[project]
name = "ttml-validator"
version = "0.1.0"
description = "Utility for validating TTML-like files against the BBC Subtitle Guidelines EBU-TT-D requirements."
authors = [ {name = "Nigel Megitt <nigel.megitt@bbc.co.uk>"} ]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "xmlschema == 4.2.0",
    "chardet == 5.2.0"
]

[project.scripts]
validate-ttml = "src.ttmlValidator:main"
collate-validation-results = "src.validationCollater:main"

[tool.poetry]
name = "ttml-validator"
version = "0.1.0"
description = "Utility for validating TTML-like files against the BBC Subtitle Guidelines EBU-TT-D requirements."
authors = ["Nigel Megitt <nigel.megitt@bbc.co.uk>"]
readme = "README.md"
packages = [
    { include = "src" },
    { include = "test" }
]

[tool.poetry.dependencies]
python = "^3.13.4"
xmlschema = "4.2.0"
chardet = "5.2.0"

[tool.poetry.group.dev.dependencies]
pydocstyle = "^6.3.0"
flake8 = "^7.3.0"
coverage = "^7.11.0"

debugpy = "^1.8.17"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "coverage>=7.9.0",
    "debugpy>=1.8.14",
]

[tool.poetry.scripts]
validate-ttml = "src.ttmlValidator:main"
collate-validation-results = "src.validationCollater:main"
